function createfigure_log(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 01-Jul-2016 13:17:41

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to semilogy
semilogy1 = semilogy(X1,YMatrix1,'LineWidth',2,'Parent',axes1);
set(semilogy1(1),'DisplayName','Arch1 ILP','Marker','^',...
    'Color',[0.494117647409439 0.184313729405403 0.556862771511078]);
set(semilogy1(2),'DisplayName','Arch2 FF','Marker','x','LineStyle','--',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(semilogy1(3),'DisplayName','Arch2 SPSA','Marker','x','LineStyle',':',...
    'Color',[0.850980401039124 0.325490206480026 0.0980392172932625]);
set(semilogy1(4),'DisplayName','Arch2 SA','Marker','x',...
    'Color',[0.929411768913269 0.694117665290833 0.125490203499794]);
set(semilogy1(5),'DisplayName','Arch4 FF','Marker','square',...
    'LineStyle','--',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(semilogy1(6),'DisplayName','Arch4 SPSA','Marker','square',...
    'LineStyle',':',...
    'Color',[0.850980401039124 0.325490206480026 0.0980392172932625]);
set(semilogy1(7),'DisplayName','Arch4 SA','Marker','square',...
    'Color',[0.929411768913269 0.694117665290833 0.125490203499794]);
set(semilogy1(8),'DisplayName','Arch5 FF','Marker','v','LineStyle','--',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(semilogy1(9),'DisplayName','Arch5 SPSA','Marker','v','LineStyle',':',...
    'Color',[0.850980401039124 0.325490206480026 0.0980392172932625]);
set(semilogy1(10),'DisplayName','Arch5 SA','Marker','v');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XGrid','on','YGrid','on','YMinorTick','on','YScale','log');
