function createfigure_log2(X1, YMatrix1)
%CREATEFIGURE2(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 01-Jul-2016 15:15:25

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to semilogy
semilogy1 = semilogy(X1,YMatrix1,'LineWidth',2,'Parent',axes1);
set(semilogy1(1),'DisplayName','A1 ILP','Marker','^',...
    'Color',[0.494117647409439 0.184313729405403 0.556862771511078]);
set(semilogy1(2),'DisplayName','A2 FF','Marker','x','LineStyle','--',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(semilogy1(3),'DisplayName','A2 SPSA','Marker','x','LineStyle',':',...
    'Color',[0.850980401039124 0.325490206480026 0.0980392172932625]);
set(semilogy1(4),'DisplayName','A2 SA','Marker','x',...
    'Color',[0.929411768913269 0.694117665290833 0.125490203499794]);
set(semilogy1(5),'DisplayName','A3 FF','Marker','square',...
    'LineStyle','--',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(semilogy1(6),'DisplayName','A3 SPSA','Marker','square',...
    'LineStyle',':',...
    'Color',[0.850980401039124 0.325490206480026 0.0980392172932625]);
set(semilogy1(7),'DisplayName','A3 SA','Marker','square',...
    'Color',[0.929411768913269 0.694117665290833 0.125490203499794]);
set(semilogy1(8),'DisplayName','A4 FF','Marker','v','LineStyle','--',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(semilogy1(9),'DisplayName','A4 SPSA','Marker','v','LineStyle',':',...
    'Color',[0.850980401039124 0.325490206480026 0.0980392172932625]);
set(semilogy1(10),'DisplayName','A4 SA','Marker','v');

% Create xlabel
xlabel('Load');

% Create ylabel
ylabel('Blocking probability');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.05 0.95]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[3e-05 1]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',12,'XGrid','on','XTick',...
    [0.05 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1],'XTickLabel',...
    {'5%','10%','20%','30%','40%','50%','60%','70%','80%','90%','100%'},'YGrid',...
    'on','YMinorTick','on','YScale','log');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','southeast','FontSize',11);

