function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 20-Jun-2016 13:56:49

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2,'Parent',axes1);
set(plot1(1),'DisplayName','A1 ILP','Marker','^',...
    'Color',[0.494117647409439 0.184313729405403 0.556862771511078]);
set(plot1(2),'DisplayName','A2 FF','Marker','x','LineStyle','--',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot1(3),'DisplayName','A2 SPSA','Marker','x','LineStyle',':',...
    'Color',[0.850980401039124 0.325490206480026 0.0980392172932625]);
set(plot1(4),'DisplayName','A2 SA','Marker','x',...
    'Color',[0.929411768913269 0.694117665290833 0.125490203499794]);
set(plot1(5),'DisplayName','A3 FF','Marker','square','LineStyle','--',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot1(6),'DisplayName','A3 SPSA','Marker','square','LineStyle',':',...
    'Color',[0.850980401039124 0.325490206480026 0.0980392172932625]);
set(plot1(7),'DisplayName','A3 SA','Marker','square',...
    'Color',[0.929411768913269 0.694117665290833 0.125490203499794]);
set(plot1(8),'DisplayName','A4 FF','Marker','v','LineStyle','--',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot1(9),'DisplayName','A4 SPSA','Marker','v','LineStyle',':',...
    'Color',[0.850980401039124 0.325490206480026 0.0980392172932625]);
set(plot1(10),'DisplayName','A4 SA','Marker','v',...
    'Color',[0.929411768913269 0.694117665290833 0.125490203499794]);

xlim(axes1, [10,600]);
% Create xlabel
xlabel('Number of PODs');

% Create ylabel
ylabel('Blocking probability');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',11,'XGrid','on','YGrid','on','YTickLabel',...
    {'0%','10%','20%','30%','40%','50%','60%','70%','80%','90%','100%'});
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.203473670785634 0.392461517932492 0.118299443075044 0.396842093969646],...
    'FontSize',11);

