function createfigure1(YMatrix1)
%CREATEFIGURE1(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 19-Jun-2016 16:46:49

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on',...
    'YTickLabel',{'0%','10%','20%','30%','40%','50%','60%','70%','80%','90%'},...
    'XTickLabel',{'0%','5%','15%','25%','35%','45%','55%','65%','75%','85%','95%'},...
    'XTick',[1 2 4 6 8 10 12 14 16 18 20]);
%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[1 20]);
box(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'LineWidth',2,'Parent',axes1);

set(plot1(1),'DisplayName','Arch1 ILP','Marker','^',...
    'Color',[0.494117647058824 0.184313725490196 0.556862745098039]);
set(plot1(2),'DisplayName','Arch2 FF','Marker','x','LineStyle','--',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot1(3),'DisplayName','Arch2 SPSA','Marker','x','LineStyle',':',...
    'Color',[0.850980401039124 0.325490206480026 0.0980392172932625]);
set(plot1(4),'DisplayName','Arch2 SA','Marker','x',...
    'Color',[0.929411768913269 0.694117665290833 0.125490203499794]);
set(plot1(5),'DisplayName','Arch4 FF','Marker','square','LineStyle','--',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot1(6),'DisplayName','Arch4 SPSA','Marker','square','LineStyle',':',...
    'Color',[0.850980401039124 0.325490206480026 0.0980392172932625]);
set(plot1(7),'DisplayName','Arch4 SA','Marker','square',...
    'Color',[0.929411768913269 0.694117665290833 0.125490203499794]);
set(plot1(8),'DisplayName','Arch5 FF','Marker','v','LineStyle','--',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot1(9),'DisplayName','Arch5 SPSA','Marker','v','LineStyle',':',...
    'Color',[0.850980401039124 0.325490206480026 0.0980392172932625]);
set(plot1(10),'DisplayName','Arch5 SA','Marker','v',...
    'Color',[0.929411768913269 0.694117665290833 0.125490203499794]);


% Create xlabel
xlabel('Load');

% Create ylabel
ylabel('Blocking probability');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.239222162252302 0.338328375059011 0.0693450731501583 0.264915154126412]);

