function createfigure(YMatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 01-Jul-2016 11:06:11

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to semilogy
semilogy1 = semilogy(YMatrix1,'Parent',axes1);
set(semilogy1(1),'DisplayName','blk(:,1)');
set(semilogy1(2),'DisplayName','blk(:,2)');
set(semilogy1(3),'DisplayName','blk(:,3)');
set(semilogy1(4),'DisplayName','blk(:,4)');
set(semilogy1(5),'DisplayName','blk(:,5)');
set(semilogy1(6),'DisplayName','blk(:,6)');
set(semilogy1(7),'DisplayName','blk(:,7)');
set(semilogy1(8),'DisplayName','blk(:,8)');
set(semilogy1(9),'DisplayName','blk(:,9)');
set(semilogy1(10),'DisplayName','blk(:,10)');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XTickLabel',{'0','0.05','0.1','0.15','0.2','0.25'},'YMinorTick',...
    'on','YScale','log');
